/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit)
    implementation(libs.guava)
    implementation("com.google.code.gson:gson:2.13.2")
    implementation("org.openjfx:javafx-controls:25.0.3")
    implementation("org.openjfx:javafx-fxml:25.0.3")
    implementation("org.openjfx:javafx-web:25.0.3")
}

javafx {
    version = "25.0.3"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.swing")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = "it.unicam.cs.mpgc.rpg125571.App"
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=javafx.graphics,javafx.media,javafx.web"
    )
}

tasks.withType<JavaExec> {
    jvmArgs(
        "--enable-native-access=javafx.graphics,javafx.media,javafx.web"
    )
}