/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg125571;
import it.unicam.cs.mpgc.rpg125571.model.Character.GameCharacter;
import it.unicam.cs.mpgc.rpg125571.model.Character.Player;
import it.unicam.cs.mpgc.rpg125571.model.Collectory.Consumable;
import it.unicam.cs.mpgc.rpg125571.model.Collectory.Equip;
import it.unicam.cs.mpgc.rpg125571.model.Collectory.Material;
import it.unicam.cs.mpgc.rpg125571.model.Stats;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

public class App{
    public static void main(String[] args) {

        // TESTER ITEM
        System.out.println("ITEM");
        System.out.println("Material");
        Material material = new Material(
                0,
                "fire_heart",
                "The heart of a fire creatur",
                true);
        System.out.println(material.getId() + " - " + material.getName() + " - " + material.getDescription());

        System.out.println("Equip");
        Equip equip = new Equip(
                0,
                "sword",
                "A simple Sword",
                false);
        System.out.println(equip.getId() + " - " + equip.getName() + " - " + equip.getDescription());

        System.out.println("Consumable");
        Consumable consumable = new Consumable(
                0,
                "Health Potion",
                "A potion that add health point",
                true,
                12);
        System.out.println(consumable.getId() + " - " + consumable.getName() + " - " + consumable.getDescription() + " - " + consumable.getConsumeValue());


        Stats stats = new Stats(2,4,30);
        Player player = new Player("Jacopo", 15, stats);
        System.out.println("NOME: " + player.getName());
        System.out.println("LIVELLO: " + player.getLevel());
        System.out.println("ATK: " + player.getStats().getAtk());
        System.out.println("DEF: " +player.getStats().getDef());
        System.out.println("HP: " +player.getStats().getMaxHp());

        System.out.println("Jacopo è stato attaccato!! (-13)");
        player.getDamage(13);
        System.out.println("Vita attuale: " + player.getCurrentHP());
    }
}
