/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg125571;
<<<<<<< Updated upstream
import it.unicam.cs.mpgc.rpg125571.model.Character.GameCharacter;
import it.unicam.cs.mpgc.rpg125571.model.Character.Player;
import it.unicam.cs.mpgc.rpg125571.model.Collectory.Consumable;
import it.unicam.cs.mpgc.rpg125571.model.Collectory.Equip;
import it.unicam.cs.mpgc.rpg125571.model.Collectory.Material;
import it.unicam.cs.mpgc.rpg125571.model.Stats;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
=======
>>>>>>> Stashed changes

public class App{
    public static void main(String[] args) {

    }
}
